<aboutusClass>:
    name:"aboutus"
    BoxLayout:
        orientation:"vertical"
        BoxLayout:
            size_hint:1, .15
            Button:
                text:"Go Back"
                background_color:1, 1, 0, .8
                on_press: app.root.current = "main"
                pos:100,100
        BoxLayout:
            orientation:"vertical"
            Label:
                text:"We are good. The best.\n\nAsk aha uncle if you do not believe"